# Recognizr Configuration File

[font]
path = "assets/font/DejaVuSansMono.ttf"

[models.detector]
path = "assets/models/scrfd_10g_bnkps.onnx"
strides = [8, 16, 32]
input_shape = [640, 640]  # [height, width] - automatically detects outputs by shape

[models.recognizer]
path = "assets/models/arcface_r100.onnx"
input_size = 112

[database]
host = "127.0.0.1"
port = 8000
username = "root"
password = "root"
namespace = "test"
database = "test"

[server]
host = "0.0.0.0"
port = 3000
